services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src/flask_postgresql_sample:/app
    depends_on:
      - postgresql
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgresql/postgres
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./for_develop/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask    

  service_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: container_pgadmin
    ports:
      - 8080:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - service_postgres

volumes:
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga
