# ベースイメージを指定
FROM python:3.12-slim

# 作業ディレクトリを設定
WORKDIR /app

# 必要なパッケージをインストール
RUN pip install --upgrade pip

# 依存関係をインストール
COPY ./src/app/app.py /app/app.py
COPY ./src/app/front/out /app/front/out 
COPY ./src/app/lib /app/lib
COPY requirements.lock requirements.lock
COPY pyproject.toml pyproject.toml
COPY README.md README.md

RUN pip install -r requirements.lock

# コマンドを実行
CMD ["python", "app.py"]
